#ifndef TRAVELLING_SALESMAN_PROBLEM_LOCALSEARCHHEURISTIC_H
#define TRAVELLING_SALESMAN_PROBLEM_LOCALSEARCHHEURISTIC_H

#include "../../UndirectedCompleteGraph.h"

void localSearch(UndirectedCompleteGraph& graph);

#endif //TRAVELLING_SALESMAN_PROBLEM_LOCALSEARCHHEURISTIC_H
