#ifndef TRAVELLING_SALESMAN_PROBLEM_CONSTRUCTIVEHEURISTIC_H
#define TRAVELLING_SALESMAN_PROBLEM_CONSTRUCTIVEHEURISTIC_H

#include <string>
using std::string;

void constructive(const string& fileName);

#endif //TRAVELLING_SALESMAN_PROBLEM_CONSTRUCTIVEHEURISTIC_H
